version: "3.8"

services:
  mysqldb:
    container_name: loginapp-mysqldb
    image: mysql:latest
    networks:
      - loginapp-network
    environment:
      - MYSQLDB_USER=root
      - MYSQLDB_ROOT_PASSWORD=********
      - MYSQLDB_DATABASE=login_app
      - MYSQL_ROOT_PASSWORD=********
    volumes:
      - "C:/Users/PASCHAL/Desktop/SpringProjects/loginapp/mysql:/var/www/html"
    ports:
      - "3307:3306"
    restart: always
#    env_file: ./ .env

  app:
    build:
      context: .
    container_name: loginapp-springboot
    image: paschalsoftdev/loginapp:v1
    ports:
      - "8090:8090"
    networks:
      - loginapp-network
    depends_on:
      - mysqldb
    environment:
      - MYSQL_HOST=loginapp-mysqldb
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=AveMaria
      - MYSQL_DATABASE=login_app
      - MYSQL_PORT=3306
      - MYSQL=`mysqldb`

#    restart: on-failure
#    env_file: ./ .env

#    environment:
#      SPRING_APPLICATION_JSON: '{
#        "spring.datasource.url" : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
#        "spring.datasource.username" : "$MYSQLDB_USER",
#        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
#        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
#        "spring.jpa.hibernate.ddl-auto" : "update"
#      }'

networks:
  loginapp-network:
    name: loginapp-network
#    volumes:
#      - .m2:C:\Users\PASCHAL\.m2
#    stdin_open: true
#    tty: true

volumes:
  dbvol:
